# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Blog\ModelBundle\Entity\Author: plaintext
        Blog\ModelBundle\Entity\User: plaintext

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        in_memory:
            memory:
                users:
                    superadmin: { password: superadmin, roles: [ 'ROLE_SUPER_ADMIN' ] }
                    admin: { password: admin, roles: [ 'ROLE_ADMIN' ] }
        user:
            entity:
              class: ModelBundle:User
              property: email
        author:
            entity:
              class: ModelBundle:Author
              property: name
        admin:
            chain:
              providers: [in_memory, author]

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        admin_area:
            pattern: ^/admin/
            anonymous: ~
            provider: admin
            access_denied_url: blog_admin_security_login
            http_basic:
            form_login:
                login_path: blog_admin_security_login
                check_path: blog_admin_security_logincheck
                default_target_path: blog_admin_post_index
            logout:
                path: blog_admin_security_logout
                target: /admin/post

        main:
            pattern: ^/
            anonymous: ~
            provider: user
            http_basic:
            form_login:
                login_path: blog_core_security_login
                check_path: blog_core_security_logincheck
                default_target_path: blog_core_post_index
            logout:
                path: blog_core_security_logout
                target: blog_core_post_index

    access_control:
        - { path: ^/admin/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/post, roles: ROLE_ADMIN }
        - { path: ^/admin, roles: ROLE_SUPER_ADMIN }

    role_hierarchy:
        ROLE_USER: ROLE_USER
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]