<?php

namespace Blog\ModelBundle\Repository;

use Blog\ModelBundle\Entity\Tag;
use Doctrine\ORM\EntityRepository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository
{

    /**
     * @param $limit
     * @return array
     */
    public function findLatest($limit)
    {
        $qb = $this->getQueryBuilder()
            ->orderBy('p.createdAt', 'desc')
            ->setMaxResults($limit);
        return $qb->getQuery()->getResult();
    }

    /**
     * Find the first post
     *
     * @return Post
     */
    public function findFirst()
    {
        $qb = $this->getQueryBuilder()
            ->orderBy('p.id', 'asc')
            ->setMaxResults(1);
        return $qb->getQuery()->getSingleResult();
    }

    /**
     * @param Tag $tag
     * @return array
     */
    public function findByTag(Tag $tag)
    {
        $qb = $this->getQueryBuilder()
            ->setParameter('tag_id', $tag->getId())
            ->innerJoin('p.tags', 't', 'WITH', 't.id = :tag_id');
        return $qb->getQuery()->getResult();
    }

    /**
     * @return \Doctrine\ORM\QueryBuilder
     */
    private function getQueryBuilder()
    {
        $em = $this->getEntityManager();
        $qb = $em->getRepository('ModelBundle:Post')
            ->createQueryBuilder('p');
        return $qb;
    }
}
