<?php

namespace Blog\ModelBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends EntityRepository
{
    /**
     * Find the first author
     *
     * @return array
     */
    public function findUsedTags()
    {
        $qb = $this->getQueryBuilder()
            ->innerJoin('t.posts', 'p');
        return $qb->getQuery()->getResult();
    }

    /**
     * @return \Doctrine\ORM\QueryBuilder
     */
    private function getQueryBuilder()
    {
        $em = $this->getEntityManager();
        $qb = $em->getRepository('ModelBundle:Tag')
            ->createQueryBuilder('t');
        return $qb;
    }
}
